### ISSUE TITLE
Cookies Importing but nothing is happening, Firefox and Chrome

### ISSUE THREAD

**Issue by michaelhill789** [Moustachauve/cookie-editor#19] opened 2019-08-16 15:41 UTC
When I paste the cookies and click on import, nothing happens.

When I paste wrong json it prompts "unable to parse json".

but when I paste correct json nothing happens

I am using updated version of Firefox and Chrome.

Need serious help.

**Comment by Moustachauve** [comment] 2019-08-20 18:58
Hi, I found the cause of your issue. Thanks for the report

When exporting cookies from Chrome, sometime the "sameSite" property will be set to "unspecified".
Ex:
    {
        "domain": ".domain.test",
        "expirationDate": 3448554548.967524,
        "hostOnly": false,
        "httpOnly": false,
        "name": "bs",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "a value"
    }

This breaks the import. 
To fix it, we need to make sure that sameSite contains only valid text, so in this case it should probably be empty.

**Comment by pandareen** [comment] 2019-12-29 09:00
Firefox(71.0) is having trouble importing `sameSite` as `unspecified`. Chrome(79.0.3945.88) is however fine importing it.

**Comment by Moustachauve** [comment] 2020-08-06 05:35
This is fixed in a recent commit and will be deploy in the next version soon

**Closed** 2020-08-06 05:36 UTC
Labels: bug
