### ISSUE TITLE
View cookies from incognito tabs

### ISSUE THREAD

**Issue by stdedos** [Moustachauve/cookie-editor#57] opened 2021-05-04 15:32 UTC
Is it possible to save cookies from incognito tabs?

The extensions strip button shows me the mainland cookies, and the devtools tab shows me an empty collection.

**Comment by Moustachauve** [comment] 2022-03-07 03:21
What error are you getting? Did you enable the extension to run in incognito mode?

I assume you are using chrome since you use the term incognito.

Here's how to allow an extension to run in incognito
- Open Incognito window
- Go to chrome://extensions
- Find the extension, click Details
- Toggle the button "Allow in Incognito" to allow the extension to run in incognito mode

**Comment by Moustachauve** [comment] 2022-03-07 03:22
I can confirm that when using incognito, I will only see the cookies from the non incognito session.

**Comment by gentue** [comment] 2022-04-28 00:49
Noticed this too, the editor doesn't seem to do anything when in incognito, which is where I use it the most

**Comment by Moustachauve** [comment] 2022-06-24 01:58
Fixed by #89, will be part of a near future update

**Closed by Moustachauve** 2022-06-24 01:58 UTC
Labels: bug, Chrome
