### ISSUE TITLE
unknown error - cookie editor

### ISSUE THREAD

**Issue by rodovir** [Moustachauve/cookie-editor#109] opened 2023-03-15 14:07 UTC
![image](https://user-images.githubusercontent.com/127963314/225333672-0eb32299-b928-4b17-b8e7-3fa352040b28.png)

There is an error when adding cookies, is it possible to fix it somehow?

**Comment by rodovir** [comment] 2023-03-15 17:28
> Дякуємо за звіт.
> 
> Ви додаєте файли cookie за допомогою кнопки "+" внизу чи за допомогою кнопки імпорту? Чи є у вас спеціальні символи в назві або описі файлу cookie? Веб-сайт використовує http чи https? Чи має він спеціальний номер порту?

Hi! adding through import > then I save them (everything works on most PCs, the problem happened with the new version)I add a cookie for the ahrefs site to log in under a certain account, there was no such problem before and it appeared a day ago.

**Comment by decuple-dream** [comment] 2023-03-18 02:36
Hi, @Moustachauve, I am also experiencing the same error.
Thanks for making a great editor.

**Comment by Ray1542-hu** [comment] 2023-03-31 09:25
Can you help me with it?

**Comment by decuple-dream** [comment] 2023-04-03 20:08
<img width="496" alt="스크린샷 2023-04-04 오전 5 07 05" src="https://user-images.githubusercontent.com/67303734/229615713-4dcc794b-ff0a-4523-bc42-9539aa6302c4.png">

I don't know when this will be fixed. It seems clear that it was distributed without going through many test cases.
There are many ways to set cookies, but I use another way because of this error.

**Comment by Moustachauve** [comment] 2023-04-03 20:23
Hey everyone,

I'd love to be able to help you resolve this issue but I can't seem to be able to reproduce this issue myself.

Do you have any specific details or cases where this happens all the time that I could try myself? If I can reproduce the error, I can make sure to fix it and check that future updates don't re-introduce this error again.

Thanks for the reports!

**Comment by decuple-dream** [comment] 2023-04-03 23:58
Hi! @Moustachauve, Thanks to answers!  This is my Export JSON data before the error popped up.
```
[
{
"name": "_fbp",
"value": "fb.1.1663031073815.709796442",
"domain": "www.example.com",
"hostOnly": true,
"path": "/user/",
"secure": false,
"httpOnly": false,
"sameSite": "no_restriction",
"session": true,
"firstPartyDomain": "",
"partitionKey": null,
"storeId": null
},
{
"name": "ASPSESSIONIDQACDBDDS",
"value": "CJOPJBEBJGKCNFOEAHKFGLFK",
"domain": "www.example.com",
"hostOnly": true,
"path": "/",
"secure": false,
"httpOnly": false,
"sameSite": "no_restriction",
"session": true,
"firstPartyDomain": "",
"partitionKey": null,
"storeId": null
},
{
"name": "_gid",
"value": "GA1.2.1990178843.1663031074",
"domain": "www.example.com",
"hostOnly": true,
"path": "/user/",
"secure": false,
"httpOnly": false,
"sameSite": "no_restriction",
"session": true,
"firstPartyDomain": "",
"partitionKey": null,
"storeId": null
},
{
"name": "_ga",
"value": "GA1.1.608297085.1655427303",
"domain": "www.example.com",
"hostOnly": true,
"path": "/user/",
"secure": false,
"httpOnly": false,
"sameSite": "no_restriction",
"session": true,
"firstPartyDomain": "",
"partitionKey": null,
"storeId": null
},
{
"name": "_ga_FYX8EYXMLS",
"value": "GS1.1.1663031073.38.1.1663031079.0.0.0",
"domain": "www.example.com",
"hostOnly": true,
"path": "/user/",
"secure": false,
"httpOnly": false,
"sameSite": "no_restriction",
"session": true,
"firstPartyDomain": "",
"partitionKey": null,
"storeId": null
}
]
```
"Import" is output, but after a while an error occurs. 

It only occurs on certain sites. Log in on a new page (Google or other site), export the cookie as JSON, and then import it again, and it will work normally.(It never happened before.)

**Comment by palmtreemarketing** [comment] 2023-04-05 17:06
I'm also experiencing this error. Specifically when I try to import via JSON. It will show "Cookies were imported" (screenshot 1) and then return "Unknown Errors" (screenshot 2).

![Screen Shot 2023-04-05 at 10 03 53 AM](https://user-images.githubusercontent.com/129984215/230152634-cc999428-ba3b-4030-ab39-f6e05db6e465.png)
![Screen Shot 2023-04-05 at 9 59 11 AM](https://user-images.githubusercontent.com/129984215/230152649-2cfe0eb5-342f-4145-90e5-db25a70da908.png)

Really enjoy the chrome extension and appreciate your work @Moustachauve. Any updates on identifying the issue or timeline to resolution?

**Comment by Moustachauve** [comment] 2023-04-05 19:30
I am still unable to reproduce the issue on my side. 
It would help to have more details that you can give me so I can isolate the error precisely.

Are you exporting cookies from a specific browser (ex: firefox) and trying to import it on another one (ex: chrome)?
Are you finding cookies online from someone else and trying to import it and it fails?

Is there a specific website that fails more than the others? Logged in or not? 

I'm sorry I still haven't found the cause of the issue.

**Comment by palmtreemarketing** [comment] 2023-04-05 23:40
For my use case, I'm importing cookies from an online source. These are cookies that allow me to login to an alternative Facebook account. The exact cookies I'm trying to import are below.


```
[
    {
        "domain": ".facebook.com",
        "expirationDate": 1662612855.850801,
        "hostOnly": false,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "bw5XX9fTepCWTWF3TnFO4Ukr"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1648458884.447426,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "0hTt6HcV2uS7VwChJ.AWUgSRGCsNrosO4SaA0cReHEF1Y.BhytWF.3B.AAA.0.0.BhytWF.AWVNa-7alUw"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1672218885.447412,
        "hostOnly": false,
        "httpOnly": true,
        "name": "xs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "19%3AIUmT5V_1dFsoBQ%3A2%3A1599540873%3A-1%3A-1%3A%3AAcXs74mOJhf6jfxa5ZTZwTH9a11NIZQ9IMuVT_tBcQ"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1672218885.447383,
        "hostOnly": false,
        "httpOnly": false,
        "name": "c_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "100051718501938"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1662612873.603047,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sb",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "bw5XX7qLlB0U2WX_mYReK2mW"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1640772890.214391,
        "hostOnly": false,
        "httpOnly": true,
        "name": "spin",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "r.1004897034_b.trunk_t.1640682888_s.1_v.2_"
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1641287675,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wd",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1366x520"
    }
]
```

**Comment by freepik19** [comment] 2023-05-26 06:49
i am having the same issue can you tell me how did you fix it please

**Closed** 2023-08-30 01:04 UTC
