### ISSUE TITLE
[Cookie-Editor] Import Button Isn't Working

### ISSUE THREAD

**Issue by Demoxing** [Moustachauve/cookie-editor#50] opened 2020-12-19 06:00 UTC
The Import button straight-up doesn't work in firefox. It just doesn't do anything when I click on import. Please help me.

https://user-images.githubusercontent.com/53024273/102682186-a36fcd80-41ed-11eb-8ceb-a09342ecaf47.mp4

**Comment by DineshSolanki** [comment] 2020-12-22 05:38
same for me.

**Comment by DineshSolanki** [comment] 2020-12-22 05:46
Duplicate of #46

**Comment by ZacharyJo** [comment] 2021-01-05 13:48
....

**Comment by Soylent17** [comment] 2021-03-17 01:48
I had this issue as well.  It turned out the import doesn't like  "sameSite": "unspecified".  I replaced instances of this with "sameSite": "lax" and everything imported fine.

**Comment by Moustachauve** [comment] 2021-03-19 16:28
I believe with the most recent version I deployed this week, this bug should be fixed, can you guys confirm that your issue is fixed please? Thank you!

**Comment by DineshSolanki** [comment] 2021-03-20 14:26
thank you @Moustachauve , It's working now.

**Comment by Moustachauve** [comment] 2021-03-21 01:44
Awesome, thank you! Sorry for the long time it took for me to update the extension.

**Closed by Moustachauve** 2021-03-21 01:44 UTC

**Comment by r3kashi** [comment] 2022-08-19 04:09
The Import button straight-up doesn't work in firefox. It just doesn't do anything when I click on import. Please help me
