### ISSUE TITLE
Got cookie from Chrome that failed to import in Firefox

### ISSUE THREAD

**Issue by ruperson** [Moustachauve/cookie-editor#74] opened 2022-03-24 01:14 UTC
Figured out that field in my cookoe json "sameSite": "None" makes import button fail to proceed import,
Maybe somehow related with #56

**Comment by Nafiu56** [comment] 2022-10-22 11:17
I cannot export cookies editor cord

**Comment by Nafiu56** [comment] 2022-10-22 11:20
I don’t have access to long in to the cookie editor

**Comment by Moustachauve** [comment] 2023-03-10 09:16
Duplicate of #56

**Closed by Moustachauve** 2023-03-10 09:16 UTC
