### ISSUE TITLE
Creating/ Editing Cookies on Tor 8.0.8 (Firefox 60.6.1esr) doesn't work

### ISSUE THREAD

**Issue by pandavova** [Moustachauve/cookie-editor#15] opened 2019-04-22 22:21 UTC
Im using http://www.html-kit.com/tools/cookietester/ as a testing site. 

Creating/ Editing Cookies doesn't work, deleting cookies works tho.

privacy.firstparty.isolate is set to false, with this disabled, the plugin worked on an older tor version. This time it didn't help.

I tried to debug the plugin and i got this Error message:
![firefox_23 04 2019_00-13-47](https://user-images.githubusercontent.com/9296158/56536036-63120500-655d-11e9-8b6d-0822d0e8b8eb.png)

Would be nice to have this fixed, really like the import function.

**Comment by Moustachauve** [comment] 2019-04-25 16:36
Thank you for your report!
The issue is occuring because that version of Firefox does not have support for the sameSite property on a cookie. I added some code to detect if a browser supports that property and to not use it if it doesn't.

It should be fixed in the next version of Cookie-Editor, I'll try to deploy it by next week.

**Comment by Moustachauve** [comment] 2019-05-02 20:10
The new version has been deployed to the different browsers store and is now available to download.

**Closed by Moustachauve** 2019-05-02 20:10 UTC
Labels: Firefox, bug
